openapi: 3.0.0
info:
  title: fCount API
  version: 1.0.0
  description: This is the API for fCount, a service to count human faces in images
servers:
  - url: 'http://localhost:3100'
    description: Local dev server
paths:
  /f-counts:
    post:
      summary: Create a new fCount request to count faces in an image
      # requestBody: 
        # todo: schema 
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      # callbacks:
        # todo: callback post request
    get:
      summary: Get a list of fCount requests
      responses:
        '200':
          description: OK
          # content:
            # todo: schema 
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /f-counts/{id}:
    get:
      summary: Get the status of a fCount request with results if available
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          # content:
            # todo: schema
        '404':
          description: Not Found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    delete:
      summary: Delete a fCount request
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error